errors:
#  semantic:
#    DomainTypeError: 0.2
#    RangeTypeError: 0.2
  local-syntactic:
#    InstanceIdentifierError: 0.1
    PropertyError: 0.1
  syntactic:
#   InstanceIdentifierError: 0.2
#   TypeError: 0.2
    PropertyError: 0.2