errors:
 semantic:
   DomainTypeError: 0.5
#   RangeTypeError: 0.2
#   InstanceAssertionError: 0.2
#   PropertyAssertionError: 0.2
 local-syntactic:
   InstanceIdentifierError: 0.1
   PropertyNameError: 0.1
#   TypeError: 0.1
# syntactic:
#   InstanceIdentifierError: 0.2
#   TypeError: 0.2
#   PropertyNameError: 0.2
#   PropertyAssertionError: 0.2